export const theme = {
  colors: {
    background: '#F6F8FB',
    surface: '#FFFFFF',
    surfaceLight: '#F0F4F8',
    primary: '#5B7FFF',
    primaryDark: '#4A6AE5',
    primaryLight: '#E8EEFF',
    secondary: '#36D1A0',
    secondaryLight: '#E5FBF3',
    accent: '#FF7EB3',
    accentLight: '#FFF0F5',
    textPrimary: '#1E2A3A',
    textSecondary: '#6B7C93',
    textTertiary: '#A0AEBF',
    sectionTitle: '#5B7FFF',
    success: '#36D1A0',
    error: '#FF6B6B',
    warning: '#FFB84D',
    rootColors: {
      port: '#5B9BD5',
      cred: '#C57BDB',
      scrib: '#7BC67B',
      magn: '#E8A54B',
      fic: '#4BC6B0',
      ent: '#6BBF6B',
    },
    morphemeColors: {
      prefix: '#FF7EB3',
      root: '#5B7FFF',
      suffix: '#36D1A0',
    },
  },
  fonts: {
    regular: 'System',
    medium: 'System-Medium',
    bold: 'System-Bold',
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
};
