export const theme = {
  colors: {
    background: '#0D0D0D',
    surface: '#1A1A1A',
    surfaceLight: '#242424',
    primary: '#FFCC00',
    primaryDark: '#E6B800',
    secondary: '#00D4AA',
    accent: '#FF6B6B',
    textPrimary: '#FFFFFF',
    textSecondary: '#B3B3B3',
    textTertiary: '#666666',
    sectionTitle: '#FFCC00',
    success: '#4CAF50',
    error: '#F44336',
    warning: '#FF9800',
    rootColors: {
      port: '#3B82A0',
      cred: '#A03B82',
      scrib: '#82A03B',
      magn: '#A06F3B',
      fic: '#3B9B82',
      ent: '#5BA03B',
    },
    morphemeColors: {
      prefix: '#FF6B6B',
      root: '#A06F3B',
      suffix: '#00D4AA',
    },
  },
  fonts: {
    regular: 'System',
    medium: 'System-Medium',
    bold: 'System-Bold',
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
};
