/**
 * Expand wordDatabaseRaw.json from ~1900 to ~8000 words
 * Strategy:
 * 1. Keep all existing data
 * 2. Add 60 new roots with derived words (~1200 new)
 * 3. Massively expand supplement categories (~5000 new)
 */

const fs = require('fs');
const path = require('path');

const existing = require('../src/data/wordDatabaseRaw.json');

// Collect existing words to avoid duplicates
const existingWords = new Set();
existing.roots.forEach(r => r.words.forEach(w => existingWords.add(w.word.toLowerCase())));
Object.values(existing.supplement).forEach(arr => arr.forEach(w => existingWords.add(w.word.toLowerCase())));

function addWord(list, word, pos, meaning) {
  if (!existingWords.has(word.toLowerCase())) {
    list.push({ word, pos, meaning });
    existingWords.add(word.toLowerCase());
  }
}

// ===================== NEW ROOTS =====================

const newRoots = [
  { id: 'cept', root: 'cept', meaning: '拿/取', origin: '拉丁语 capere', color: '#4A90D9', level: 2,
    words: [
      ['accept','v','接受'],['concept','n','概念'],['except','prep','除了'],['exception','n','例外'],
      ['intercept','v','拦截'],['perception','n','感知'],['reception','n','接待'],['receptive','a','善于接受的'],
      ['deception','n','欺骗'],['inception','n','开始'],['precept','n','训诫'],['susceptible','a','易受影响的'],
    ]},
  { id: 'cede', root: 'cede', meaning: '走/让步', origin: '拉丁语 cedere', color: '#D94A7A', level: 3,
    words: [
      ['proceed','v','继续'],['procedure','n','程序'],['process','n','过程'],['procession','n','队列'],
      ['precede','v','先于'],['precedent','n','先例'],['succeed','v','成功'],['success','n','成功'],
      ['exceed','v','超越'],['excess','n','过量'],['access','n','通道'],['accessible','a','可接近的'],
      ['concede','v','承认'],['recede','v','后退'],['ancestor','n','祖先'],
    ]},
  { id: 'claim', root: 'claim', meaning: '喊/叫', origin: '拉丁语 clamare', color: '#7A4AD9', level: 4,
    words: [
      ['claim','v','声称'],['exclaim','v','惊叫'],['proclaim','v','宣布'],['proclamation','n','公告'],
      ['acclaim','v','欢呼'],['disclaim','v','否认'],['reclaim','v','回收'],
    ]},
  { id: 'clud', root: 'clud', meaning: '关闭', origin: '拉丁语 claudere', color: '#D9A04A', level: 4,
    words: [
      ['include','v','包含'],['exclude','v','排除'],['conclude','v','结论'],['conclusion','n','结论'],
      ['exclusive','a','独占的'],['inclusive','a','包容的'],['preclude','v','排除'],['seclude','v','隔离'],
      ['disclose','v','揭露'],['enclose','v','围住'],['closet','n','壁橱'],
    ]},
  { id: 'cogn', root: 'cogn', meaning: '知道/认识', origin: '拉丁语 cognoscere', color: '#4AD9A0', level: 5,
    words: [
      ['recognize','v','认出'],['recognition','n','认可'],['cognitive','a','认知的'],['cognition','n','认知'],
      ['incognito','a','匿名的'],['diagnose','v','诊断'],['diagnosis','n','诊断'],['prognosis','n','预测'],
    ]},
  { id: 'cord', root: 'cord', meaning: '心', origin: '拉丁语 cor', color: '#D94A4A', level: 5,
    words: [
      ['record','v','记录'],['accord','n','一致'],['according','prep','根据'],['accordion','n','手风琴'],
      ['discord','n','不和'],['core','n','核心'],['courage','n','勇气'],['encourage','v','鼓励'],
      ['discourage','v','使灰心'],['cordial','a','热情的'],
    ]},
  { id: 'crit', root: 'crit', meaning: '判断', origin: '希腊语 krinein', color: '#4AD9D9', level: 5,
    words: [
      ['critic','n','评论家'],['critical','a','关键的'],['criticize','v','批评'],['criterion','n','标准'],
      ['crisis','n','危机'],['crime','n','犯罪'],['criminal','n','罪犯'],['discriminate','v','歧视'],
    ]},
  { id: 'dem', root: 'dem', meaning: '人民', origin: '希腊语 demos', color: '#9B4AD9', level: 5,
    words: [
      ['democracy','n','民主'],['democratic','a','民主的'],['demonstrate','v','示范'],['demonstration','n','示威'],
      ['epidemic','n','流行病'],['pandemic','n','大流行'],['demography','n','人口学'],
    ]},
  { id: 'doc', root: 'doc', meaning: '教', origin: '拉丁语 docere', color: '#D9D94A', level: 4,
    words: [
      ['doctor','n','医生'],['document','n','文件'],['documentary','n','纪录片'],['doctrine','n','教义'],
      ['documentation','n','文档'],['indoctrinate','v','灌输'],
    ]},
  { id: 'dom', root: 'dom', meaning: '统治/家', origin: '拉丁语 dominus', color: '#4A7AD9', level: 5,
    words: [
      ['dominate','v','支配'],['dominant','a','占主导的'],['domestic','a','国内的'],['domain','n','领域'],
      ['kingdom','n','王国'],['freedom','n','自由'],['wisdom','n','智慧'],['predominant','a','主要的'],
    ]},
  { id: 'dur', root: 'dur', meaning: '持久/硬', origin: '拉丁语 durus', color: '#D94AD9', level: 6,
    words: [
      ['durable','a','耐用的'],['duration','n','持续时间'],['endure','v','忍受'],['endurance','n','耐力'],
      ['during','prep','在...期间'],['obdurate','a','固执的'],
    ]},
  { id: 'fect', root: 'fect', meaning: '做/影响', origin: '拉丁语 facere', color: '#7AD94A', level: 3,
    words: [
      ['effect','n','效果'],['effective','a','有效的'],['affect','v','影响'],['affection','n','感情'],
      ['defect','n','缺陷'],['perfect','a','完美的'],['infect','v','感染'],['infection','n','感染'],
      ['defective','a','有缺陷的'],['confection','n','糖果'],
    ]},
  { id: 'fig', root: 'fig', meaning: '形状/塑造', origin: '拉丁语 fingere', color: '#D97A4A', level: 6,
    words: [
      ['figure','n','数字/人物'],['configure','v','配置'],['configuration','n','配置'],['disfigure','v','毁容'],
      ['figurative','a','比喻的'],['fiction','n','小说'],['fictional','a','虚构的'],
    ]},
  { id: 'firm', root: 'firm', meaning: '坚固', origin: '拉丁语 firmus', color: '#4AD97A', level: 4,
    words: [
      ['confirm','v','确认'],['affirm','v','肯定'],['firm','a','坚固的'],['infirm','a','体弱的'],
      ['confirmation','n','确认'],['affirmative','a','肯定的'],
    ]},
  { id: 'flect', root: 'flect', meaning: '弯曲', origin: '拉丁语 flectere', color: '#D94A9B', level: 6,
    words: [
      ['reflect','v','反射/反思'],['reflection','n','反射'],['flexible','a','灵活的'],['flexibility','n','灵活性'],
      ['deflect','v','偏转'],['inflect','v','变调'],
    ]},
  { id: 'gress', root: 'gress', meaning: '走/步', origin: '拉丁语 gradi', color: '#4AD9D9', level: 4,
    words: [
      ['progress','n','进步'],['progressive','a','进步的'],['aggressive','a','侵略的'],['aggression','n','侵略'],
      ['congress','n','国会'],['regress','v','退步'],['digress','v','离题'],['transgress','v','违反'],
    ]},
  { id: 'hab', root: 'hab', meaning: '拥有/居住', origin: '拉丁语 habere', color: '#9BD94A', level: 5,
    words: [
      ['habit','n','习惯'],['inhabit','v','居住'],['inhabitant','n','居民'],['habitat','n','栖息地'],
      ['exhibit','v','展示'],['exhibition','n','展览'],['prohibit','v','禁止'],['rehabilitation','n','康复'],
    ]},
  { id: 'ject2', root: 'ject', meaning: '投/扔', origin: '拉丁语 jacere', color: '#D9D97A', level: 2,
    words: [
      ['subject','n','主题'],['subjective','a','主观的'],['object','n','物体'],['objective','a','客观的'],
      ['injection','n','注射'],['projection','n','投影'],['trajectory','n','轨迹'],['eject','v','弹出'],
      ['objection','n','反对'],
    ]},
  { id: 'junct', root: 'junct', meaning: '连接', origin: '拉丁语 jungere', color: '#4A4AD9', level: 6,
    words: [
      ['junction','n','交叉口'],['conjunction','n','连词'],['adjunct','n','附属物'],['disjunction','n','分离'],
      ['injunction','n','禁令'],['juncture','n','关头'],
    ]},
  { id: 'labor', root: 'labor', meaning: '工作/劳动', origin: '拉丁语 laborare', color: '#D94A4A', level: 4,
    words: [
      ['labor','n','劳动'],['laboratory','n','实验室'],['elaborate','a','精心的'],['collaborate','v','合作'],
      ['collaboration','n','合作'],['laborious','a','费力的'],
    ]},
  { id: 'lat', root: 'lat', meaning: '带来/承载', origin: '拉丁语 latus', color: '#4AD94A', level: 6,
    words: [
      ['translate','v','翻译'],['translation','n','翻译'],['relate','v','关联'],['relation','n','关系'],
      ['relative','a','相对的'],['correlate','v','使相关'],['legislation','n','立法'],['legislate','v','立法'],
      ['dilate','v','扩张'],['collateral','n','抵押品'],
    ]},
  { id: 'lect', root: 'lect', meaning: '选择/读', origin: '拉丁语 legere', color: '#D9A07A', level: 3,
    words: [
      ['select','v','选择'],['selection','n','选择'],['collect','v','收集'],['collection','n','收藏'],
      ['elect','v','选举'],['election','n','选举'],['lecture','n','讲座'],['intellectual','a','智力的'],
      ['neglect','v','忽视'],['dialect','n','方言'],['elegant','a','优雅的'],
    ]},
  { id: 'liber', root: 'liber', meaning: '自由', origin: '拉丁语 liber', color: '#7AD9A0', level: 5,
    words: [
      ['liberal','a','自由的'],['liberty','n','自由'],['liberate','v','解放'],['liberation','n','解放'],
      ['deliberate','a','故意的'],['deliver','v','递送'],['delivery','n','递送'],
    ]},
  { id: 'lingu', root: 'lingu', meaning: '语言/舌', origin: '拉丁语 lingua', color: '#A04AD9', level: 6,
    words: [
      ['language','n','语言'],['linguistic','a','语言学的'],['bilingual','a','双语的'],['multilingual','a','多语的'],
      ['linguist','n','语言学家'],
    ]},
  { id: 'liter', root: 'liter', meaning: '文字/字母', origin: '拉丁语 litera', color: '#D9A04A', level: 5,
    words: [
      ['literature','n','文学'],['literary','a','文学的'],['literacy','n','识字'],['literal','a','字面的'],
      ['literally','ad','字面上'],['illiterate','a','文盲的'],['literate','a','有文化的'],
    ]},
  { id: 'mand', root: 'mand', meaning: '命令/托付', origin: '拉丁语 mandare', color: '#4AD9D9', level: 5,
    words: [
      ['command','v','命令'],['commander','n','指挥官'],['demand','v','要求'],['mandate','n','授权'],
      ['mandatory','a','强制的'],['recommend','v','推荐'],['recommendation','n','推荐'],['remand','v','还押'],
    ]},
  { id: 'medi', root: 'medi', meaning: '中间', origin: '拉丁语 medius', color: '#D97A7A', level: 5,
    words: [
      ['media','n','媒体'],['medium','n','媒介'],['mediate','v','调解'],['mediator','n','调停者'],
      ['medieval','a','中世纪的'],['immediate','a','立即的'],['immediately','ad','立即'],['intermediate','a','中间的'],
      ['Mediterranean','n','地中海'],
    ]},
  { id: 'ment', root: 'ment', meaning: '心/想', origin: '拉丁语 mens', color: '#7A7AD9', level: 4,
    words: [
      ['mental','a','精神的'],['mention','v','提到'],['comment','n','评论'],['commentary','n','解说'],
      ['mentor','n','导师'],['monument','n','纪念碑'],['fundamental','a','基本的'],['sentiment','n','情绪'],
      ['sentimental','a','感伤的'],['experiment','n','实验'],['experimental','a','实验的'],
    ]},
  { id: 'migr', root: 'migr', meaning: '迁移', origin: '拉丁语 migrare', color: '#D9D94A', level: 6,
    words: [
      ['migrate','v','迁移'],['migration','n','迁移'],['immigrant','n','移民'],['immigration','n','移民'],
      ['emigrate','v','移居国外'],['emigrant','n','移居者'],
    ]},
  { id: 'miss', root: 'miss', meaning: '发送/投', origin: '拉丁语 mittere', color: '#4A9BD9', level: 3,
    words: [
      ['mission','n','任务'],['missile','n','导弹'],['dismiss','v','解散'],['admission','n','准入'],
      ['commission','n','委员会'],['emission','n','排放'],['permission','n','许可'],['submission','n','提交'],
      ['transmission','n','传输'],['promise','n','承诺'],['compromise','n','妥协'],['premise','n','前提'],
    ]},
  { id: 'mob', root: 'mob', meaning: '移动', origin: '拉丁语 movere', color: '#D94A7A', level: 4,
    words: [
      ['mobile','a','移动的'],['automobile','n','汽车'],['immobile','a','不动的'],['mobilize','v','动员'],
      ['motion','n','运动'],['emotion','n','情感'],['emotional','a','情绪的'],['promote','v','促进'],
      ['promotion','n','促销'],['remote','a','遥远的'],['remove','v','移除'],['removal','n','移除'],
      ['moment','n','时刻'],['momentum','n','动力'],
    ]},
  { id: 'norm', root: 'norm', meaning: '规则/标准', origin: '拉丁语 norma', color: '#7AD94A', level: 5,
    words: [
      ['normal','a','正常的'],['abnormal','a','不正常的'],['norm','n','规范'],['enormous','a','巨大的'],
      ['normalize','v','使正常化'],['informal','a','非正式的'],
    ]},
  { id: 'not', root: 'not', meaning: '标记/知道', origin: '拉丁语 notare', color: '#D9A07A', level: 4,
    words: [
      ['note','n','笔记'],['notice','v','注意'],['notion','n','概念'],['notable','a','值得注意的'],
      ['notify','v','通知'],['notification','n','通知'],['notorious','a','臭名昭著的'],['annotate','v','注释'],
      ['denote','v','表示'],['connote','v','暗示'],
    ]},
  { id: 'nov2', root: 'nov', meaning: '新', origin: '拉丁语 novus', color: '#4AD9A0', level: 5,
    words: [
      ['novel','n','小说'],['novelty','n','新奇'],['innovate','v','创新'],['innovation','n','创新'],
      ['innovative','a','创新的'],['renovate','v','翻新'],['renovation','n','翻新'],
    ]},
  { id: 'numer', root: 'numer', meaning: '数字', origin: '拉丁语 numerus', color: '#D94AD9', level: 6,
    words: [
      ['number','n','数字'],['numerous','a','众多的'],['numeral','n','数字'],['enumerate','v','列举'],
      ['numerical','a','数字的'],['innumerable','a','无数的'],
    ]},
  { id: 'opt', root: 'opt', meaning: '选择/最佳', origin: '拉丁语 optare', color: '#9BD9D9', level: 5,
    words: [
      ['option','n','选项'],['optional','a','可选的'],['adopt','v','采纳'],['adoption','n','采纳'],
      ['optimal','a','最优的'],['optimize','v','优化'],['optimistic','a','乐观的'],['pessimistic','a','悲观的'],
    ]},
  { id: 'ord', root: 'ord', meaning: '顺序/命令', origin: '拉丁语 ordo', color: '#D97AD9', level: 5,
    words: [
      ['order','n','顺序'],['ordinary','a','普通的'],['extraordinary','a','非凡的'],['disorder','n','紊乱'],
      ['coordinate','v','协调'],['subordinate','a','从属的'],['ordinal','a','序数的'],
    ]},
  { id: 'pact', root: 'pact', meaning: '固定/约定', origin: '拉丁语 pangere', color: '#4AD97A', level: 6,
    words: [
      ['impact','n','影响'],['compact','a','紧凑的'],['pact','n','协定'],['package','n','包裹'],
      ['pace','n','步伐'],['capacity','n','容量'],
    ]},
  { id: 'par', root: 'par', meaning: '准备/相等', origin: '拉丁语 parare', color: '#D9D97A', level: 4,
    words: [
      ['prepare','v','准备'],['preparation','n','准备'],['compare','v','比较'],['comparison','n','比较'],
      ['repair','v','修理'],['separate','v','分离'],['separation','n','分离'],['apparent','a','明显的'],
      ['apparently','ad','显然'],['transparent','a','透明的'],
    ]},
  { id: 'pater', root: 'pater', meaning: '父亲/祖国', origin: '拉丁语 pater', color: '#A04AD9', level: 7,
    words: [
      ['pattern','n','模式'],['patron','n','赞助人'],['patriot','n','爱国者'],['patriotic','a','爱国的'],
      ['paternal','a','父亲的'],['patrimony','n','遗产'],['expatriate','n','侨民'],
    ]},
  { id: 'pel', root: 'pel', meaning: '驱动/推', origin: '拉丁语 pellere', color: '#D94A9B', level: 5,
    words: [
      ['compel','v','强迫'],['compelling','a','引人注目的'],['expel','v','驱逐'],['impel','v','推动'],
      ['propel','v','推进'],['repel','v','排斥'],['appeal','v','呼吁'],['pulse','n','脉搏'],['impulse','n','冲动'],
    ]},
  { id: 'peri', root: 'peri', meaning: '尝试/经验', origin: '拉丁语 periri', color: '#7AD9D9', level: 5,
    words: [
      ['experience','n','经验'],['experienced','a','有经验的'],['expert','n','专家'],['expertise','n','专业知识'],
      ['experiment','n','实验'],['peril','n','危险'],['perilous','a','危险的'],
    ]},
  { id: 'phil', root: 'phil', meaning: '爱/热爱', origin: '希腊语 philos', color: '#D9A04A', level: 7,
    words: [
      ['philosophy','n','哲学'],['philosopher','n','哲学家'],['philanthropist','n','慈善家'],['philanthropy','n','慈善'],
      ['bibliophile','n','书迷'],
    ]},
  { id: 'phon', root: 'phon', meaning: '声音', origin: '希腊语 phone', color: '#4A7AD9', level: 6,
    words: [
      ['phone','n','电话'],['phonetic','a','语音的'],['microphone','n','麦克风'],['symphony','n','交响乐'],
      ['euphony','n','悦耳'],['cacophony','n','刺耳声'],
    ]},
  { id: 'photo', root: 'photo', meaning: '光', origin: '希腊语 phos', color: '#D9D94A', level: 6,
    words: [
      ['photograph','n','照片'],['photography','n','摄影'],['photosynthesis','n','光合作用'],['photon','n','光子'],
      ['photocopy','n','复印'],
    ]},
  { id: 'plex', root: 'plex', meaning: '折叠/编织', origin: '拉丁语 plectere', color: '#4AD94A', level: 6,
    words: [
      ['complex','a','复杂的'],['complexity','n','复杂性'],['simple','a','简单的'],['simplify','v','简化'],
      ['complicate','v','使复杂'],['complicated','a','复杂的'],['duplicate','v','复制'],['multiply','v','乘'],
      ['multiple','a','多重的'],['imply','v','暗示'],['implication','n','含义'],['apply','v','申请'],
      ['application','n','申请'],['supply','v','供应'],['reply','v','回复'],
    ]},
  { id: 'popul', root: 'popul', meaning: '人民', origin: '拉丁语 populus', color: '#D97A4A', level: 5,
    words: [
      ['popular','a','流行的'],['popularity','n','人气'],['population','n','人口'],['populate','v','居住于'],
      ['unpopular','a','不受欢迎的'],['public','a','公共的'],['publish','v','出版'],['republic','n','共和国'],
      ['publication','n','出版物'],['publicity','n','宣传'],
    ]},
  { id: 'port2', root: 'port', meaning: '部分/分享', origin: '拉丁语 portio', color: '#4A4AD9', level: 4,
    words: [
      ['portion','n','部分'],['proportion','n','比例'],['proportional','a','比例的'],
    ]},
  { id: 'prim', root: 'prim', meaning: '第一/首要', origin: '拉丁语 primus', color: '#D94A4A', level: 5,
    words: [
      ['primary','a','主要的'],['prime','a','首要的'],['primitive','a','原始的'],['prince','n','王子'],
      ['principal','a','主要的'],['principle','n','原则'],['priority','n','优先'],['privilege','n','特权'],
    ]},
  { id: 'psych', root: 'psych', meaning: '心灵/精神', origin: '希腊语 psyche', color: '#9B4AD9', level: 7,
    words: [
      ['psychology','n','心理学'],['psychological','a','心理的'],['psychologist','n','心理学家'],
      ['psychiatry','n','精神病学'],['psyche','n','心灵'],['psychic','a','灵异的'],
    ]},
  { id: 'quest', root: 'quest', meaning: '寻找/询问', origin: '拉丁语 quaerere', color: '#D9D97A', level: 4,
    words: [
      ['question','n','问题'],['request','v','请求'],['require','v','需要'],['requirement','n','要求'],
      ['acquire','v','获得'],['acquisition','n','获取'],['inquire','v','询问'],['inquiry','n','调查'],
      ['conquer','v','征服'],['conquest','n','征服'],
    ]},
  { id: 'radi', root: 'radi', meaning: '光线/射线', origin: '拉丁语 radius', color: '#4AD9A0', level: 6,
    words: [
      ['radio','n','收音机'],['radiation','n','辐射'],['radical','a','激进的'],['radius','n','半径'],
      ['radiant','a','光辉的'],['radiate','v','辐射'],
    ]},
  { id: 'rupt2', root: 'rupt', meaning: '断裂', origin: '拉丁语 rumpere', color: '#D97AD9', level: 3,
    words: [
      ['interrupt','v','中断'],['interruption','n','中断'],['corrupt','a','腐败的'],['corruption','n','腐败'],
      ['erupt','v','爆发'],['eruption','n','爆发'],['abrupt','a','突然的'],['bankrupt','a','破产的'],
      ['bankruptcy','n','破产'],['disruptive','a','破坏性的'],
    ]},
  { id: 'sacr', root: 'sacr', meaning: '神圣', origin: '拉丁语 sacer', color: '#7A4AD9', level: 7,
    words: [
      ['sacred','a','神圣的'],['sacrifice','n','牺牲'],['sacrament','n','圣礼'],['consecrate','v','奉献'],
      ['desecrate','v','亵渎'],['sacrilege','n','亵渎'],
    ]},
  { id: 'scope', root: 'scope', meaning: '看/范围', origin: '希腊语 skopein', color: '#D9A07A', level: 6,
    words: [
      ['scope','n','范围'],['microscope','n','显微镜'],['telescope','n','望远镜'],['horoscope','n','星座运势'],
      ['kaleidoscope','n','万花筒'],['stethoscope','n','听诊器'],
    ]},
  { id: 'sequ', root: 'sequ', meaning: '跟随', origin: '拉丁语 sequi', color: '#4AD97A', level: 5,
    words: [
      ['sequence','n','顺序'],['consequence','n','后果'],['consequently','ad','因此'],['subsequent','a','随后的'],
      ['pursue','v','追求'],['pursuit','n','追求'],['execute','v','执行'],['execution','n','执行'],
      ['prosecute','v','起诉'],['consecutive','a','连续的'],
    ]},
  { id: 'serv', root: 'serv', meaning: '服务/保持', origin: '拉丁语 servare', color: '#D9D94A', level: 3,
    words: [
      ['serve','v','服务'],['service','n','服务'],['server','n','服务器'],['servant','n','仆人'],
      ['observe','v','观察'],['observation','n','观察'],['preserve','v','保存'],['reserve','v','预约'],
      ['reservation','n','预订'],['conserve','v','保存'],['conservation','n','保护'],['conservative','a','保守的'],
      ['deserve','v','值得'],
    ]},
  { id: 'simil', root: 'simil', meaning: '相似', origin: '拉丁语 similis', color: '#7AD9A0', level: 5,
    words: [
      ['similar','a','相似的'],['similarity','n','相似性'],['simulate','v','模拟'],['simulation','n','模拟'],
      ['simultaneous','a','同时的'],['assemble','v','组装'],['assembly','n','集会'],['resemble','v','类似'],
    ]},
  { id: 'soci', root: 'soci', meaning: '同伴/社会', origin: '拉丁语 socius', color: '#D94A7A', level: 4,
    words: [
      ['social','a','社会的'],['society','n','社会'],['associate','v','联合'],['association','n','协会'],
      ['socialism','n','社会主义'],['sociology','n','社会学'],['antisocial','a','反社会的'],
    ]},
  { id: 'sol', root: 'sol', meaning: '单独/太阳', origin: '拉丁语 solus', color: '#4A9BD9', level: 5,
    words: [
      ['solution','n','解决方案'],['solve','v','解决'],['resolve','v','决心'],['resolution','n','决议'],
      ['dissolve','v','溶解'],['absolute','a','绝对的'],['solar','a','太阳的'],['sole','a','唯一的'],
      ['isolate','v','隔离'],['isolation','n','隔离'],['solitary','a','孤独的'],['solo','a','独自的'],
    ]},
  { id: 'spec', root: 'spec', meaning: '特殊/种类', origin: '拉丁语 species', color: '#D9A04A', level: 4,
    words: [
      ['special','a','特别的'],['specialist','n','专家'],['specialize','v','专攻'],['specific','a','具体的'],
      ['specification','n','规格'],['species','n','物种'],['specimen','n','样本'],['specify','v','指定'],
      ['especially','ad','尤其'],
    ]},
  { id: 'spir', root: 'spir', meaning: '呼吸/精神', origin: '拉丁语 spirare', color: '#7A7AD9', level: 5,
    words: [
      ['inspire','v','激励'],['inspiration','n','灵感'],['spirit','n','精神'],['spiritual','a','精神的'],
      ['aspire','v','渴望'],['aspiration','n','抱负'],['expire','v','到期'],['conspire','v','密谋'],
      ['conspiracy','n','阴谋'],['perspire','v','出汗'],['respiratory','a','呼吸的'],
    ]},
  { id: 'stat', root: 'stat', meaning: '站立/状态', origin: '拉丁语 stare', color: '#D94AD9', level: 3,
    words: [
      ['state','n','状态'],['statement','n','声明'],['estate','n','地产'],['status','n','地位'],
      ['statue','n','雕像'],['stable','a','稳定的'],['establish','v','建立'],['establishment','n','机构'],
      ['install','v','安装'],['installation','n','安装'],['instance','n','实例'],['instant','a','即时的'],
      ['constant','a','不变的'],['circumstance','n','情况'],['substance','n','物质'],['substantial','a','大量的'],
      ['obstacle','n','障碍'],['statistics','n','统计'],['station','n','车站'],['stationary','a','静止的'],
    ]},
  { id: 'tact', root: 'tact', meaning: '触碰', origin: '拉丁语 tangere', color: '#4AD9D9', level: 6,
    words: [
      ['contact','n','联系'],['intact','a','完整的'],['tactic','n','战术'],['tactical','a','战术的'],
      ['tangible','a','有形的'],['contagious','a','传染的'],
    ]},
  { id: 'terr', root: 'terr', meaning: '土地/恐惧', origin: '拉丁语 terra', color: '#D97A4A', level: 5,
    words: [
      ['territory','n','领土'],['territorial','a','领土的'],['terrain','n','地形'],['terrace','n','露台'],
      ['terrestrial','a','陆地的'],['Mediterranean','n','地中海'],['terror','n','恐怖'],['terrorist','n','恐怖分子'],
      ['terrible','a','可怕的'],['terrific','a','极好的'],['terrify','v','使恐惧'],['deter','v','阻止'],
      ['deterrent','n','威慑'],
    ]},
  { id: 'therm', root: 'therm', meaning: '热', origin: '希腊语 thermos', color: '#D9D94A', level: 7,
    words: [
      ['thermal','a','热的'],['thermometer','n','温度计'],['thermostat','n','恒温器'],['geothermal','a','地热的'],
      ['hypothermia','n','体温过低'],
    ]},
  { id: 'tract2', root: 'tract', meaning: '拉/拖', origin: '拉丁语 trahere', color: '#4A7AD9', level: 3,
    words: [
      ['abstract','a','抽象的'],['distract','v','分散'],['distraction','n','分心'],['subtract','v','减去'],
      ['tractor','n','拖拉机'],['attractive','a','有吸引力的'],['attraction','n','吸引'],
    ]},
  { id: 'tribut', root: 'tribut', meaning: '给予', origin: '拉丁语 tribuere', color: '#D94A4A', level: 5,
    words: [
      ['contribute','v','贡献'],['contribution','n','贡献'],['distribute','v','分配'],['distribution','n','分配'],
      ['attribute','v','归因于'],['tribute','n','致敬'],
    ]},
  { id: 'uni', root: 'uni', meaning: '一/统一', origin: '拉丁语 unus', color: '#4AD94A', level: 4,
    words: [
      ['unit','n','单位'],['unite','v','联合'],['unity','n','统一'],['uniform','n','制服'],
      ['unique','a','独特的'],['universe','n','宇宙'],['universal','a','普遍的'],['university','n','大学'],
      ['union','n','联盟'],['reunion','n','团聚'],
    ]},
  { id: 'vac', root: 'vac', meaning: '空', origin: '拉丁语 vacare', color: '#D97AD9', level: 6,
    words: [
      ['vacation','n','假期'],['vacant','a','空的'],['vacancy','n','空缺'],['vacuum','n','真空'],
      ['evacuate','v','撤离'],['evacuation','n','疏散'],['vain','a','徒劳的'],
    ]},
  { id: 'vari', root: 'vari', meaning: '变化', origin: '拉丁语 varius', color: '#7AD97A', level: 5,
    words: [
      ['vary','v','变化'],['variety','n','多样性'],['various','a','各种的'],['variable','a','可变的'],
      ['variation','n','变化'],['variant','n','变体'],['invariable','a','不变的'],
    ]},
  { id: 'vict', root: 'vict', meaning: '征服', origin: '拉丁语 vincere', color: '#D9A04A', level: 6,
    words: [
      ['victory','n','胜利'],['victim','n','受害者'],['convince','v','说服'],['conviction','n','信念'],
      ['invincible','a','不可战胜的'],['province','n','省份'],['provincial','a','省的'],['evict','v','驱逐'],
    ]},
  { id: 'volv', root: 'volv', meaning: '滚/转', origin: '拉丁语 volvere', color: '#4A4AD9', level: 4,
    words: [
      ['involve','v','涉及'],['involvement','n','参与'],['evolve','v','进化'],['evolution','n','进化'],
      ['revolution','n','革命'],['revolutionary','a','革命性的'],['revolve','v','旋转'],['resolve','v','决心'],
      ['volume','n','体积'],['volunteer','n','志愿者'],
    ]},
];

// ===================== EXPANDED SUPPLEMENTS =====================

const supplementExpansion = {
  '高频动词': [
    ['achieve','v','实现'],['acknowledge','v','承认'],['adapt','v','适应'],['address','v','解决'],
    ['adjust','v','调整'],['admire','v','钦佩'],['admit','v','承认'],['advance','v','前进'],
    ['advise','v','建议'],['afford','v','负担得起'],['agree','v','同意'],['aim','v','目标'],
    ['allow','v','允许'],['announce','v','宣布'],['anticipate','v','预期'],['apologize','v','道歉'],
    ['appreciate','v','感激'],['approach','v','接近'],['approve','v','批准'],['argue','v','争论'],
    ['arise','v','出现'],['arrange','v','安排'],['assign','v','分配'],['assist','v','协助'],
    ['assume','v','假设'],['assure','v','保证'],['attach','v','附上'],['attempt','v','尝试'],
    ['attend','v','参加'],['avoid','v','避免'],['ban','v','禁止'],['bargain','v','讨价还价'],
    ['bear','v','承受'],['beat','v','打败'],['behave','v','表现'],['belong','v','属于'],
    ['bend','v','弯曲'],['bet','v','打赌'],['bind','v','绑定'],['bite','v','咬'],
    ['blame','v','责备'],['bleed','v','流血'],['blend','v','混合'],['bless','v','保佑'],
    ['block','v','阻挡'],['blow','v','吹'],['boast','v','自夸'],['bother','v','打扰'],
    ['bounce','v','弹跳'],['bow','v','鞠躬'],['breathe','v','呼吸'],['breed','v','繁殖'],
    ['broadcast','v','广播'],['brush','v','刷'],['budget','v','预算'],['burden','v','负担'],
    ['burst','v','爆裂'],['calculate','v','计算'],['campaign','v','竞选'],['capture','v','捕获'],
    ['cast','v','投射'],['celebrate','v','庆祝'],['challenge','v','挑战'],['chase','v','追赶'],
    ['chat','v','聊天'],['cheat','v','欺骗'],['check','v','检查'],['cheer','v','欢呼'],
    ['choke','v','窒息'],['circulate','v','循环'],['classify','v','分类'],['climb','v','攀登'],
    ['cling','v','紧贴'],['coach','v','指导'],['collapse','v','崩溃'],['combine','v','结合'],
    ['comfort','v','安慰'],['communicate','v','沟通'],['commute','v','通勤'],['compensate','v','补偿'],
    ['compete','v','竞争'],['complain','v','抱怨'],['concentrate','v','集中'],['confess','v','坦白'],
    ['confine','v','限制'],['confront','v','面对'],['confuse','v','困惑'],['connect','v','连接'],
    ['conquer','v','征服'],['consult','v','咨询'],['consume','v','消耗'],['contain','v','包含'],
    ['contribute','v','贡献'],['convince','v','说服'],['cope','v','应对'],['crash','v','坠毁'],
    ['crawl','v','爬行'],['cultivate','v','培养'],['cure','v','治愈'],['dare','v','敢'],
    ['debate','v','辩论'],['decay','v','腐烂'],['deceive','v','欺骗'],['declare','v','宣布'],
    ['decline','v','下降'],['decorate','v','装饰'],['decrease','v','减少'],['defeat','v','击败'],
    ['defend','v','防御'],['define','v','定义'],['delay','v','延迟'],['delete','v','删除'],
    ['delight','v','使高兴'],['deliver','v','交付'],['deny','v','否认'],['depart','v','离开'],
    ['depend','v','依赖'],['deposit','v','存放'],['deprive','v','剥夺'],['derive','v','源自'],
    ['deserve','v','值得'],['desire','v','渴望'],['despise','v','鄙视'],['detect','v','检测'],
    ['determine','v','决定'],['develop','v','发展'],['devote','v','奉献'],['dig','v','挖'],
    ['diminish','v','减少'],['dip','v','蘸'],['direct','v','指导'],['disappoint','v','使失望'],
    ['discipline','v','训练'],['disguise','v','伪装'],['display','v','展示'],['dispose','v','处理'],
    ['distinguish','v','区分'],['distort','v','歪曲'],['distribute','v','分配'],['disturb','v','打扰'],
    ['dive','v','潜水'],['divide','v','划分'],['donate','v','捐赠'],['doubt','v','怀疑'],
    ['drag','v','拖拽'],['drain','v','排水'],['draw','v','画'],['drift','v','漂流'],
    ['drill','v','钻'],['drop','v','掉落'],['drown','v','淹没'],['earn','v','赚取'],
    ['ease','v','缓解'],['educate','v','教育'],['eliminate','v','消除'],['embarrass','v','使尴尬'],
    ['embrace','v','拥抱'],['emerge','v','出现'],['emphasize','v','强调'],['employ','v','雇用'],
    ['enable','v','使能够'],['encounter','v','遭遇'],['endure','v','忍受'],['engage','v','从事'],
    ['enhance','v','增强'],['ensure','v','确保'],['entertain','v','娱乐'],['equip','v','装备'],
    ['escape','v','逃跑'],['estimate','v','估计'],['evaluate','v','评估'],['exaggerate','v','夸大'],
    ['examine','v','检查'],['exchange','v','交换'],['excite','v','兴奋'],['exclude','v','排除'],
    ['excuse','v','原谅'],['exercise','v','锻炼'],['exhaust','v','耗尽'],['exist','v','存在'],
    ['expand','v','扩展'],['expect','v','期望'],['explore','v','探索'],['expose','v','暴露'],
    ['extend','v','延伸'],['extract','v','提取'],['fade','v','褪色'],['fail','v','失败'],
    ['fancy','v','喜欢'],['fascinate','v','着迷'],['fasten','v','系紧'],['feast','v','宴会'],
    ['feature','v','特色'],['feed','v','喂养'],['fetch','v','取来'],['filter','v','过滤'],
    ['finance','v','资助'],['flash','v','闪光'],['flatten','v','压平'],['flee','v','逃离'],
    ['float','v','漂浮'],['flood','v','洪水'],['flourish','v','繁荣'],['fold','v','折叠'],
    ['forbid','v','禁止'],['forecast','v','预报'],['forgive','v','原谅'],['format','v','格式化'],
    ['found','v','创建'],['freeze','v','冻结'],['frighten','v','使恐惧'],['frown','v','皱眉'],
    ['fulfill','v','实现'],['function','v','运作'],['fund','v','资助'],['furnish','v','提供'],
    ['gain','v','获得'],['gamble','v','赌博'],['gather','v','聚集'],['gaze','v','凝视'],
    ['generate','v','产生'],['gesture','v','做手势'],['glance','v','扫视'],['govern','v','治理'],
    ['grab','v','抓取'],['grant','v','授予'],['grasp','v','抓紧'],['greet','v','问候'],
    ['grind','v','磨碎'],['grip','v','紧握'],['guarantee','v','保证'],['guard','v','守卫'],
    ['guess','v','猜测'],['guide','v','指导'],['halt','v','停止'],['handle','v','处理'],
    ['hang','v','悬挂'],['harvest','v','收割'],['hasten','v','加速'],['hate','v','恨'],
    ['heal','v','愈合'],['hesitate','v','犹豫'],['highlight','v','突出'],['hire','v','雇用'],
    ['honor','v','尊敬'],['host','v','主办'],['hunt','v','打猎'],['hurry','v','匆忙'],
    ['identify','v','识别'],['ignore','v','忽略'],['illustrate','v','说明'],['imagine','v','想象'],
    ['imitate','v','模仿'],['implement','v','实施'],['impose','v','强加'],['impress','v','印象深刻'],
    ['indicate','v','表明'],['induce','v','诱导'],['inform','v','通知'],['inherit','v','继承'],
    ['initiate','v','发起'],['injure','v','受伤'],['insert','v','插入'],['insist','v','坚持'],
    ['install','v','安装'],['instruct','v','指导'],['insure','v','保险'],['intend','v','打算'],
    ['interpret','v','解释'],['interrupt','v','中断'],['introduce','v','介绍'],['invade','v','入侵'],
    ['invest','v','投资'],['investigate','v','调查'],['invite','v','邀请'],['irritate','v','刺激'],
    ['justify','v','证明'],['knock','v','敲'],['label','v','标记'],['lack','v','缺乏'],
    ['launch','v','启动'],['lean','v','倾斜'],['leap','v','跳跃'],['lend','v','借出'],
    ['liberate','v','解放'],['lift','v','举起'],['limit','v','限制'],['link','v','链接'],
    ['load','v','装载'],['locate','v','定位'],['lower','v','降低'],['maintain','v','维护'],
    ['manage','v','管理'],['manifest','v','显示'],['manipulate','v','操纵'],['manufacture','v','制造'],
    ['march','v','行军'],['master','v','掌握'],['match','v','匹配'],['measure','v','测量'],
    ['melt','v','融化'],['memorize','v','记忆'],['merge','v','合并'],['migrate','v','迁移'],
    ['minimize','v','最小化'],['modify','v','修改'],['monitor','v','监控'],['motivate','v','激励'],
    ['mount','v','安装'],['multiply','v','乘'],['murder','v','谋杀'],['neglect','v','忽视'],
    ['negotiate','v','谈判'],['nod','v','点头'],['nominate','v','提名'],['obey','v','服从'],
    ['oblige','v','迫使'],['obtain','v','获得'],['occupy','v','占据'],['offend','v','冒犯'],
    ['operate','v','操作'],['oppose','v','反对'],['orbit','v','环绕'],['organize','v','组织'],
    ['orient','v','定向'],['originate','v','起源'],['overcome','v','克服'],['overlook','v','忽视'],
    ['overtake','v','超过'],['owe','v','欠'],['panic','v','恐慌'],['participate','v','参与'],
    ['pause','v','暂停'],['penetrate','v','穿透'],['perceive','v','感知'],['persist','v','坚持'],
    ['persuade','v','劝说'],['pioneer','v','开拓'],['plant','v','种植'],['plead','v','恳求'],
    ['pledge','v','保证'],['plot','v','策划'],['plunge','v','跳入'],['polish','v','抛光'],
    ['postpone','v','推迟'],['pour','v','倒'],['pray','v','祈祷'],['predict','v','预测'],
    ['prefer','v','偏好'],['preserve','v','保存'],['press','v','按'],['pretend','v','假装'],
    ['prevail','v','盛行'],['prevent','v','阻止'],['print','v','打印'],['proceed','v','继续'],
    ['process','v','处理'],['prohibit','v','禁止'],['promote','v','提升'],['prompt','v','促使'],
    ['pronounce','v','发音'],['propose','v','提议'],['protest','v','抗议'],['prove','v','证明'],
    ['provoke','v','激怒'],['purchase','v','购买'],['pursue','v','追求'],['qualify','v','有资格'],
    ['quit','v','退出'],['quote','v','引用'],['raise','v','提高'],['range','v','排列'],
    ['rate','v','评价'],['react','v','反应'],['realize','v','意识到'],['recall','v','回忆'],
    ['reckon','v','估计'],['recover','v','恢复'],['recruit','v','招募'],['recycle','v','回收'],
    ['reduce','v','减少'],['refer','v','参考'],['reflect','v','反映'],['reform','v','改革'],
    ['refuse','v','拒绝'],['register','v','注册'],['regulate','v','调节'],['reinforce','v','加强'],
    ['reject','v','拒绝'],['release','v','释放'],['rely','v','依赖'],['remain','v','保持'],
    ['remark','v','评论'],['remedy','v','补救'],['remind','v','提醒'],['render','v','使成为'],
    ['renew','v','更新'],['replace','v','替换'],['represent','v','代表'],['reproduce','v','复制'],
    ['rescue','v','营救'],['resemble','v','类似'],['resent','v','愤恨'],['resign','v','辞职'],
    ['resist','v','抵抗'],['resort','v','求助'],['restore','v','恢复'],['restrain','v','抑制'],
    ['restrict','v','限制'],['retain','v','保留'],['retire','v','退休'],['retreat','v','撤退'],
    ['reveal','v','揭示'],['reverse','v','反转'],['revise','v','修订'],['revive','v','复苏'],
    ['reward','v','奖励'],['rip','v','撕裂'],['risk','v','冒险'],['rob','v','抢劫'],
    ['rotate','v','旋转'],['ruin','v','毁灭'],['sacrifice','v','牺牲'],['satisfy','v','满足'],
    ['scatter','v','散布'],['schedule','v','安排'],['scratch','v','抓'],['seal','v','密封'],
    ['seek','v','寻找'],['seize','v','抓住'],['settle','v','解决'],['shape','v','塑造'],
    ['shed','v','流出'],['shelter','v','庇护'],['shift','v','转移'],['shine','v','闪耀'],
    ['shrink','v','收缩'],['sigh','v','叹气'],['signal','v','发信号'],['simplify','v','简化'],
    ['skip','v','跳过'],['slam','v','猛撞'],['slap','v','拍打'],['slip','v','滑倒'],
    ['smash','v','粉碎'],['snap','v','折断'],['soak','v','浸泡'],['soar','v','高飞'],
    ['solve','v','解决'],['sort','v','分类'],['spare','v','节省'],['speculate','v','推测'],
    ['spin','v','旋转'],['split','v','分裂'],['spoil','v','溺爱'],['sponsor','v','赞助'],
    ['spray','v','喷洒'],['spread','v','传播'],['squeeze','v','挤压'],['stain','v','弄脏'],
    ['stare','v','凝视'],['starve','v','挨饿'],['steal','v','偷'],['steer','v','驾驶'],
    ['stem','v','阻止'],['stick','v','粘贴'],['stimulate','v','刺激'],['stir','v','搅拌'],
    ['store','v','储存'],['strain','v','拉紧'],['strengthen','v','加强'],['stretch','v','伸展'],
    ['strike','v','罢工'],['strip','v','剥去'],['strive','v','努力'],['stroke','v','中风'],
    ['struggle','v','奋斗'],['stuff','v','塞满'],['stumble','v','绊倒'],['submit','v','提交'],
    ['subscribe','v','订阅'],['substitute','v','替代'],['succeed','v','成功'],['suffer','v','遭受'],
    ['suggest','v','建议'],['summarize','v','总结'],['supervise','v','监督'],['supplement','v','补充'],
    ['suppose','v','假设'],['suppress','v','压制'],['surpass','v','超越'],['surrender','v','投降'],
    ['surround','v','围绕'],['survey','v','调查'],['survive','v','存活'],['suspect','v','怀疑'],
    ['suspend','v','暂停'],['sustain','v','维持'],['swallow','v','吞咽'],['swap','v','交换'],
    ['swear','v','发誓'],['sweep','v','扫'],['swell','v','膨胀'],['switch','v','切换'],
    ['sympathize','v','同情'],['tackle','v','处理'],['tempt','v','诱惑'],['tend','v','倾向'],
    ['terminate','v','终止'],['testify','v','作证'],['threaten','v','威胁'],['thrill','v','激动'],
    ['tighten','v','收紧'],['tolerate','v','容忍'],['torture','v','折磨'],['trace','v','追踪'],
    ['transform','v','转变'],['transmit','v','传输'],['transport','v','运输'],['trap','v','陷阱'],
    ['treasure','v','珍惜'],['treat','v','对待'],['tremble','v','颤抖'],['trigger','v','触发'],
    ['triumph','v','胜利'],['undertake','v','承担'],['unfold','v','展开'],['unify','v','统一'],
    ['update','v','更新'],['upgrade','v','升级'],['urge','v','敦促'],['utilize','v','利用'],
    ['vanish','v','消失'],['venture','v','冒险'],['verify','v','验证'],['violate','v','违反'],
    ['volunteer','v','自愿'],['vote','v','投票'],['wander','v','漫步'],['warn','v','警告'],
    ['weaken','v','削弱'],['weave','v','编织'],['weigh','v','称重'],['whisper','v','低语'],
    ['widen','v','加宽'],['wipe','v','擦'],['withdraw','v','撤回'],['witness','v','目击'],
    ['wonder','v','想知道'],['worship','v','崇拜'],['wrap','v','包裹'],['yell','v','喊叫'],
    ['yield','v','产出'],
  ],
  '高频名词': [
    ['absence','n','缺席'],['abundance','n','丰富'],['academy','n','学院'],['accent','n','口音'],
    ['acid','n','酸'],['acre','n','英亩'],['adolescent','n','青少年'],['adventure','n','冒险'],
    ['advocate','n','倡导者'],['affair','n','事务'],['agenda','n','议程'],['agent','n','代理人'],
    ['agriculture','n','农业'],['aid','n','援助'],['aircraft','n','飞机'],['alarm','n','警报'],
    ['alcohol','n','酒精'],['alien','n','外星人'],['alliance','n','联盟'],['allowance','n','津贴'],
    ['altitude','n','海拔'],['ambassador','n','大使'],['ambition','n','野心'],['amendment','n','修正案'],
    ['analogy','n','类比'],['analysis','n','分析'],['analyst','n','分析师'],['anchor','n','锚'],
    ['angel','n','天使'],['anger','n','愤怒'],['angle','n','角度'],['anguish','n','痛苦'],
    ['anniversary','n','周年'],['antenna','n','天线'],['anxiety','n','焦虑'],['apparatus','n','装置'],
    ['appetite','n','食欲'],['appliance','n','器具'],['applicant','n','申请人'],['appointment','n','任命'],
    ['appraisal','n','评价'],['apprentice','n','学徒'],['architect','n','建筑师'],['archive','n','档案'],
    ['arena','n','竞技场'],['armor','n','盔甲'],['array','n','数组'],['arrow','n','箭头'],
    ['article','n','文章'],['aspect','n','方面'],['assault','n','攻击'],['asset','n','资产'],
    ['assignment','n','任务'],['assumption','n','假设'],['atmosphere','n','气氛'],['atom','n','原子'],
    ['attorney','n','律师'],['auction','n','拍卖'],['audit','n','审计'],['authority','n','权威'],
    ['avalanche','n','雪崩'],['avenue','n','大道'],['bachelor','n','学士'],['backbone','n','骨干'],
    ['bacteria','n','细菌'],['badge','n','徽章'],['ballot','n','选票'],['bandwidth','n','带宽'],
    ['banner','n','横幅'],['barrier','n','障碍'],['basement','n','地下室'],['basin','n','盆地'],
    ['basis','n','基础'],['batch','n','批次'],['battery','n','电池'],['battlefield','n','战场'],
    ['beam','n','梁'],['beast','n','野兽'],['behalf','n','代表'],['benchmark','n','基准'],
    ['benefit','n','利益'],['beverage','n','饮料'],['bias','n','偏见'],['blade','n','刀片'],
    ['blanket','n','毯子'],['blast','n','爆炸'],['blend','n','混合'],['blessing','n','祝福'],
    ['blueprint','n','蓝图'],['bonus','n','奖金'],['booth','n','展位'],['boundary','n','边界'],
    ['bracket','n','括号'],['brand','n','品牌'],['breakthrough','n','突破'],['breed','n','品种'],
    ['breeze','n','微风'],['brick','n','砖'],['bride','n','新娘'],['broker','n','经纪人'],
    ['bronze','n','青铜'],['bubble','n','泡沫'],['bucket','n','水桶'],['buff','n','爱好者'],
    ['bulletin','n','公告'],['bunch','n','一束'],['bureau','n','局'],['cabin','n','小屋'],
    ['cabinet','n','内阁'],['cable','n','电缆'],['calendar','n','日历'],['campus','n','校园'],
    ['candidate','n','候选人'],['canon','n','准则'],['canvas','n','画布'],['cape','n','海角'],
    ['carbon','n','碳'],['cargo','n','货物'],['carnival','n','嘉年华'],['carpet','n','地毯'],
    ['carriage','n','马车'],['cascade','n','瀑布'],['catalog','n','目录'],['cathedral','n','大教堂'],
    ['cattle','n','牛'],['caution','n','谨慎'],['cavity','n','腔'],['celebrity','n','名人'],
    ['cell','n','细胞'],['cement','n','水泥'],['census','n','人口普查'],['ceremony','n','仪式'],
    ['certificate','n','证书'],['chamber','n','房间'],['champion','n','冠军'],['channel','n','频道'],
    ['chaos','n','混乱'],['chapter','n','章节'],['charity','n','慈善'],['charm','n','魅力'],
    ['chart','n','图表'],['charter','n','宪章'],['chimney','n','烟囱'],['chip','n','芯片'],
    ['chord','n','和弦'],['chunk','n','大块'],['circuit','n','电路'],['circulation','n','流通'],
    ['citizen','n','公民'],['civilization','n','文明'],['clause','n','条款'],['client','n','客户'],
    ['cliff','n','悬崖'],['climate','n','气候'],['clinic','n','诊所'],['cluster','n','集群'],
    ['coalition','n','联盟'],['code','n','代码'],['coin','n','硬币'],['colleague','n','同事'],
    ['colony','n','殖民地'],['column','n','列'],['combat','n','战斗'],['comedy','n','喜剧'],
    ['commerce','n','商业'],['committee','n','委员会'],['commodity','n','商品'],['companion','n','伴侣'],
    ['compartment','n','隔间'],['compass','n','指南针'],['compensation','n','补偿'],['competence','n','能力'],
    ['competitor','n','竞争者'],['complement','n','补充'],['complication','n','并发症'],['component','n','组件'],
    ['compound','n','化合物'],['compromise','n','妥协'],['concession','n','让步'],['concrete','n','混凝土'],
    ['conference','n','会议'],['confession','n','忏悔'],['confidence','n','信心'],['conflict','n','冲突'],
    ['congregation','n','会众'],['conscience','n','良心'],['consensus','n','共识'],['consent','n','同意'],
    ['conservation','n','保护'],['constitution','n','宪法'],['consultant','n','顾问'],['contempt','n','蔑视'],
    ['continent','n','大陆'],['contractor','n','承包商'],['contradiction','n','矛盾'],['controversy','n','争议'],
    ['convention','n','惯例'],['copper','n','铜'],['copyright','n','版权'],['corridor','n','走廊'],
    ['costume','n','服装'],['cottage','n','小屋'],['council','n','理事会'],['counselor','n','辅导员'],
    ['counter','n','柜台'],['courtesy','n','礼貌'],['craft','n','手艺'],['crane','n','起重机'],
    ['crater','n','火山口'],['creature','n','生物'],['crew','n','船员'],['crop','n','作物'],
    ['crown','n','王冠'],['crush','n','迷恋'],['crystal','n','水晶'],['cue','n','暗示'],
    ['curiosity','n','好奇心'],['curriculum','n','课程'],['curtain','n','窗帘'],['custody','n','监管'],
    ['custom','n','习俗'],['cycle','n','周期'],['cylinder','n','圆柱'],['database','n','数据库'],
    ['deadline','n','截止日期'],['debate','n','辩论'],['debt','n','债务'],['decade','n','十年'],
    ['deficit','n','赤字'],['delegate','n','代表'],['density','n','密度'],['departure','n','出发'],
    ['deposit','n','存款'],['depression','n','抑郁'],['deputy','n','副手'],['descendant','n','后代'],
    ['destiny','n','命运'],['detective','n','侦探'],['device','n','设备'],['dialogue','n','对话'],
    ['diameter','n','直径'],['diamond','n','钻石'],['dignity','n','尊严'],['dilemma','n','困境'],
    ['dimension','n','维度'],['diplomat','n','外交官'],['directory','n','目录'],['disability','n','残疾'],
    ['discipline','n','纪律'],['discourse','n','论述'],['discovery','n','发现'],['discrimination','n','歧视'],
    ['dispute','n','争端'],['distinction','n','区别'],['doctrine','n','学说'],['domain','n','领域'],
    ['donation','n','捐赠'],['dose','n','剂量'],['draft','n','草稿'],['drama','n','戏剧'],
    ['drawback','n','缺点'],['drought','n','干旱'],['dump','n','垃圾场'],['dust','n','灰尘'],
    ['dwelling','n','住所'],['dynamic','n','动力'],['echo','n','回声'],['economy','n','经济'],
    ['ecosystem','n','生态系统'],['edition','n','版本'],['educator','n','教育者'],['efficiency','n','效率'],
    ['electrode','n','电极'],['element','n','元素'],['embassy','n','大使馆'],['emergency','n','紧急情况'],
    ['emperor','n','皇帝'],['empire','n','帝国'],['encounter','n','遭遇'],['encyclopedia','n','百科全书'],
    ['endeavor','n','努力'],['engagement','n','订婚'],['engine','n','引擎'],['enterprise','n','企业'],
    ['enthusiasm','n','热情'],['entity','n','实体'],['entrepreneur','n','企业家'],['envelope','n','信封'],
    ['environment','n','环境'],['episode','n','插曲'],['equality','n','平等'],['equation','n','方程'],
    ['era','n','时代'],['essay','n','论文'],['essence','n','本质'],['estate','n','地产'],
    ['ethic','n','伦理'],['evidence','n','证据'],['evolution','n','进化'],['exception','n','例外'],
    ['excess','n','过量'],['exchange','n','交换'],['exhibit','n','展品'],['expedition','n','远征'],
    ['expenditure','n','支出'],['exposure','n','曝光'],['extension','n','扩展'],['extract','n','摘要'],
    ['fabric','n','织物'],['facility','n','设施'],['faculty','n','学院'],['famine','n','饥荒'],
    ['fare','n','票价'],['fate','n','命运'],['fatigue','n','疲劳'],['feast','n','盛宴'],
    ['feature','n','特征'],['federation','n','联邦'],['feedback','n','反馈'],['ferry','n','渡轮'],
    ['festival','n','节日'],['fiber','n','纤维'],['fiction','n','虚构'],['flame','n','火焰'],
    ['flaw','n','缺陷'],['flesh','n','肉'],['fleet','n','舰队'],['flock','n','群'],
    ['flora','n','植物群'],['foam','n','泡沫'],['folk','n','人们'],['formula','n','公式'],
    ['fortune','n','运气'],['fossil','n','化石'],['foundation','n','基金会'],['fraction','n','分数'],
    ['fragment','n','碎片'],['framework','n','框架'],['franchise','n','特许经营'],['freight','n','货运'],
    ['frontier','n','边界'],['frost','n','霜'],['frustration','n','挫折'],['fuel','n','燃料'],
    ['funeral','n','葬礼'],['furniture','n','家具'],['fury','n','狂怒'],['galaxy','n','银河系'],
    ['gallery','n','画廊'],['gap','n','差距'],['garage','n','车库'],['garbage','n','垃圾'],
    ['garment','n','服装'],['gear','n','齿轮'],['gender','n','性别'],['gene','n','基因'],
    ['genius','n','天才'],['genre','n','类型'],['gesture','n','手势'],['glacier','n','冰川'],
    ['globe','n','地球仪'],['glory','n','荣耀'],['gossip','n','八卦'],['grace','n','优雅'],
    ['grain','n','谷物'],['gravity','n','重力'],['grief','n','悲伤'],['grocery','n','杂货'],
    ['gross','n','总额'],['guarantee','n','保证'],['guardian','n','监护人'],['guideline','n','指南'],
    ['guilt','n','罪行'],['harbor','n','港口'],['hardware','n','硬件'],['harmony','n','和谐'],
    ['harvest','n','收获'],['hazard','n','危害'],['headquarters','n','总部'],['heap','n','堆'],
    ['heritage','n','遗产'],['hierarchy','n','等级制度'],['highlight','n','亮点'],['hint','n','暗示'],
    ['hormone','n','激素'],['horizon','n','地平线'],['hostage','n','人质'],['household','n','家庭'],
    ['humidity','n','湿度'],['hurricane','n','飓风'],['hydrogen','n','氢'],['hypothesis','n','假设'],
    ['icon','n','图标'],['ideology','n','意识形态'],['illusion','n','幻觉'],['image','n','图像'],
    ['immigrant','n','移民'],['immunity','n','免疫'],['incentive','n','激励'],['incident','n','事件'],
    ['inclination','n','倾向'],['index','n','索引'],['indicator','n','指标'],['industry','n','工业'],
    ['infant','n','婴儿'],['inflation','n','通货膨胀'],['influence','n','影响'],['infrastructure','n','基础设施'],
    ['ingredient','n','成分'],['initiative','n','主动性'],['innovation','n','创新'],['input','n','输入'],
    ['insight','n','洞察力'],['inspection','n','检查'],['installment','n','分期付款'],['institution','n','机构'],
    ['instrument','n','工具'],['insurance','n','保险'],['integrity','n','正直'],['intellect','n','智力'],
    ['intelligence','n','智力'],['intensity','n','强度'],['intention','n','意图'],['interaction','n','互动'],
    ['interest','n','兴趣'],['interference','n','干涉'],['interior','n','内部'],['interval','n','间隔'],
    ['intervention','n','干预'],['inventory','n','库存'],['investment','n','投资'],['investor','n','投资者'],
    ['irrigation','n','灌溉'],['isolation','n','隔离'],['issue','n','问题'],['ivory','n','象牙'],
    ['jail','n','监狱'],['jaw','n','颌'],['jet','n','喷射'],['journal','n','期刊'],
    ['jury','n','陪审团'],['justice','n','正义'],['juvenile','n','少年'],['kidney','n','肾脏'],
    ['kingdom','n','王国'],['kit','n','套件'],['knot','n','结'],['label','n','标签'],
    ['ladder','n','梯子'],['landlord','n','房东'],['landscape','n','风景'],['lane','n','车道'],
    ['laser','n','激光'],['latitude','n','纬度'],['lawn','n','草坪'],['lawsuit','n','诉讼'],
    ['layer','n','层'],['layout','n','布局'],['league','n','联盟'],['leak','n','泄漏'],
    ['legend','n','传说'],['legislation','n','立法'],['leisure','n','休闲'],['lens','n','镜头'],
    ['lever','n','杠杆'],['liability','n','责任'],['lifetime','n','一生'],['limb','n','肢体'],
    ['limestone','n','石灰石'],['linen','n','亚麻布'],['liver','n','肝脏'],['loan','n','贷款'],
    ['lobby','n','大厅'],['logic','n','逻辑'],['longitude','n','经度'],['lottery','n','彩票'],
    ['luggage','n','行李'],['lumber','n','木材'],['lung','n','肺'],['luxury','n','奢侈'],
    ['machinery','n','机械'],['magazine','n','杂志'],['magistrate','n','地方法官'],['mainstream','n','主流'],
    ['majority','n','多数'],['mammal','n','哺乳动物'],['mansion','n','豪宅'],['manual','n','手册'],
    ['manuscript','n','手稿'],['marathon','n','马拉松'],['margin','n','边距'],['masterpiece','n','杰作'],
    ['mechanism','n','机制'],['membrane','n','膜'],['memorial','n','纪念碑'],['merchandise','n','商品'],
    ['mercy','n','仁慈'],['merit','n','优点'],['metabolism','n','新陈代谢'],['metaphor','n','隐喻'],
    ['microbe','n','微生物'],['migration','n','迁移'],['milestone','n','里程碑'],['militia','n','民兵'],
    ['mineral','n','矿物'],['minister','n','部长'],['minority','n','少数'],['miracle','n','奇迹'],
    ['mischief','n','恶作剧'],['missile','n','导弹'],['moisture','n','水分'],['molecule','n','分子'],
    ['monarchy','n','君主制'],['monopoly','n','垄断'],['mortgage','n','抵押'],['motto','n','座右铭'],
    ['mound','n','土丘'],['muscle','n','肌肉'],['mutual','n','相互'],['mystery','n','神秘'],
    ['myth','n','神话'],['narrative','n','叙事'],['navigation','n','导航'],['necessity','n','必要性'],
    ['needle','n','针'],['neighborhood','n','社区'],['nerve','n','神经'],['network','n','网络'],
    ['neutral','n','中立'],['nightmare','n','噩梦'],['nitrogen','n','氮'],['nobility','n','贵族'],
    ['nominee','n','被提名者'],['norm','n','规范'],['nostalgia','n','怀旧'],['notion','n','概念'],
    ['novelty','n','新颖'],['nucleus','n','核'],['nuisance','n','讨厌的东西'],['nutrition','n','营养'],
    ['oath','n','誓言'],['obesity','n','肥胖'],['objection','n','反对'],['obligation','n','义务'],
    ['offspring','n','后代'],['opera','n','歌剧'],['opponent','n','对手'],['orbit','n','轨道'],
    ['orchestra','n','管弦乐队'],['organ','n','器官'],['organism','n','有机体'],['orientation','n','方向'],
    ['origin','n','起源'],['orphan','n','孤儿'],['outbreak','n','爆发'],['outcome','n','结果'],
    ['outfit','n','服装'],['outlet','n','出口'],['outline','n','大纲'],['output','n','输出'],
    ['outrage','n','愤怒'],['overhead','n','开销'],['overlap','n','重叠'],['oversight','n','监督'],
    ['oxygen','n','氧气'],['oyster','n','牡蛎'],['palace','n','宫殿'],['palm','n','手掌'],
    ['panel','n','面板'],['parade','n','游行'],['paradise','n','天堂'],['paragraph','n','段落'],
    ['parliament','n','议会'],['particle','n','粒子'],['passion','n','热情'],['passport','n','护照'],
    ['patent','n','专利'],['patience','n','耐心'],['pathway','n','路径'],['patrol','n','巡逻'],
    ['patron','n','赞助人'],['peak','n','高峰'],['peasant','n','农民'],['penalty','n','处罚'],
    ['pension','n','养老金'],['percentage','n','百分比'],['perspective','n','视角'],['petition','n','请愿'],
    ['petroleum','n','石油'],['pharmacy','n','药房'],['phase','n','阶段'],['phenomenon','n','现象'],
    ['pioneer','n','先驱'],['pipeline','n','管道'],['plague','n','瘟疫'],['platform','n','平台'],
    ['pledge','n','承诺'],['plot','n','情节'],['plug','n','插头'],['plumber','n','水管工'],
    ['poetry','n','诗歌'],['pole','n','杆'],['policy','n','政策'],['politician','n','政治家'],
    ['poll','n','投票'],['pollution','n','污染'],['pond','n','池塘'],['portfolio','n','作品集'],
    ['portrait','n','肖像'],['possession','n','占有'],['poster','n','海报'],['pottery','n','陶器'],
    ['poultry','n','家禽'],['poverty','n','贫困'],['powder','n','粉末'],['precision','n','精确'],
    ['predator','n','捕食者'],['prejudice','n','偏见'],['premium','n','保费'],['prescription','n','处方'],
    ['presence','n','存在'],['presidency','n','总统任期'],['prey','n','猎物'],['pride','n','骄傲'],
    ['priest','n','牧师'],['princess','n','公主'],['prison','n','监狱'],['privacy','n','隐私'],
    ['probe','n','探测'],['procedure','n','程序'],['proceeds','n','收入'],['proclamation','n','宣告'],
    ['productivity','n','生产力'],['profession','n','职业'],['profile','n','简介'],['profit','n','利润'],
    ['program','n','程序'],['propaganda','n','宣传'],['property','n','财产'],['proportion','n','比例'],
    ['proposal','n','提案'],['prosperity','n','繁荣'],['protein','n','蛋白质'],['protocol','n','协议'],
    ['province','n','省份'],['provision','n','规定'],['psychology','n','心理学'],['pulse','n','脉搏'],
    ['puzzle','n','谜题'],['pyramid','n','金字塔'],['quantity','n','数量'],['quantum','n','量子'],
    ['quarantine','n','隔离'],['quota','n','配额'],['radar','n','雷达'],['rage','n','愤怒'],
    ['rally','n','集会'],['ranch','n','牧场'],['ratio','n','比率'],['realm','n','领域'],
    ['rebellion','n','叛乱'],['recipe','n','食谱'],['recognition','n','认可'],['recreation','n','娱乐'],
    ['referendum','n','公投'],['reflection','n','反映'],['refuge','n','避难'],['regime','n','政权'],
    ['regiment','n','团'],['region','n','地区'],['registration','n','注册'],['regulation','n','规定'],
    ['reign','n','统治'],['relief','n','救济'],['religion','n','宗教'],['remedy','n','补救'],
    ['Renaissance','n','文艺复兴'],['renewal','n','更新'],['rent','n','租金'],['reputation','n','声誉'],
    ['reservoir','n','水库'],['residence','n','住宅'],['resident','n','居民'],['resistance','n','抵抗'],
    ['resolution','n','分辨率'],['resource','n','资源'],['response','n','回应'],['restoration','n','恢复'],
    ['restriction','n','限制'],['retail','n','零售'],['revenge','n','复仇'],['revenue','n','收入'],
    ['revolution','n','革命'],['rhetoric','n','修辞'],['rhythm','n','节奏'],['riot','n','暴动'],
    ['ritual','n','仪式'],['rival','n','竞争对手'],['robot','n','机器人'],['rocket','n','火箭'],
    ['rope','n','绳子'],['roster','n','名册'],['routine','n','日常'],['rumor','n','谣言'],
    ['salary','n','薪水'],['sample','n','样本'],['sanction','n','制裁'],['sanctuary','n','保护区'],
    ['satellite','n','卫星'],['scandal','n','丑闻'],['scenario','n','场景'],['scheme','n','方案'],
    ['scholarship','n','奖学金'],['sculpture','n','雕塑'],['sector','n','部门'],['segment','n','段'],
    ['semester','n','学期'],['senate','n','参议院'],['sensation','n','感觉'],['session','n','会议'],
    ['shaft','n','轴'],['shame','n','羞耻'],['siege','n','围攻'],['signature','n','签名'],
    ['silicon','n','硅'],['skeleton','n','骨架'],['sketch','n','素描'],['skull','n','头骨'],
    ['slab','n','板'],['slavery','n','奴隶制'],['slot','n','插槽'],['slum','n','贫民窟'],
    ['smartphone','n','智能手机'],['sodium','n','钠'],['software','n','软件'],['solidarity','n','团结'],
    ['ソlution','n','solution'],['sovereignty','n','主权'],['spacecraft','n','航天器'],['span','n','跨度'],
    ['specification','n','规范'],['specimen','n','标本'],['spectrum','n','光谱'],['sphere','n','球体'],
    ['spine','n','脊柱'],['spokesman','n','发言人'],['spouse','n','配偶'],['squad','n','小队'],
    ['stake','n','利害关系'],['stance','n','立场'],['staple','n','主食'],['statute','n','法规'],
    ['stereotype','n','刻板印象'],['stimulus','n','刺激'],['stock','n','股票'],['storage','n','存储'],
    ['strategy','n','策略'],['stream','n','溪流'],['stride','n','大步'],['strip','n','条'],
    ['stroke','n','中风'],['suburb','n','郊区'],['successor','n','继任者'],['summit','n','峰会'],
    ['supplement','n','补充'],['surplus','n','盈余'],['surveillance','n','监视'],['suspect','n','嫌疑人'],
    ['suspension','n','悬浮'],['swamp','n','沼泽'],['sword','n','剑'],['symbol','n','符号'],
    ['symptom','n','症状'],['syndrome','n','综合症'],['synthesis','n','合成'],['tablet','n','平板电脑'],
    ['tactic','n','战术'],['tag','n','标签'],['tale','n','故事'],['talent','n','才能'],
    ['tank','n','坦克'],['tariff','n','关税'],['technique','n','技术'],['telescope','n','望远镜'],
    ['temple','n','寺庙'],['tendency','n','趋势'],['tension','n','紧张'],['tenure','n','任期'],
    ['terminal','n','终端'],['terrace','n','露台'],['territory','n','领土'],['testimony','n','证词'],
    ['textile','n','纺织品'],['therapy','n','治疗'],['thesis','n','论文'],['throne','n','王位'],
    ['tide','n','潮汐'],['timber','n','木材'],['tissue','n','组织'],['token','n','代币'],
    ['tolerance','n','容忍'],['tomb','n','坟墓'],['torch','n','火炬'],['tournament','n','锦标赛'],
    ['tower','n','塔'],['trace','n','痕迹'],['trademark','n','商标'],['tradition','n','传统'],
    ['tragedy','n','悲剧'],['trait','n','特征'],['transaction','n','交易'],['transition','n','过渡'],
    ['trauma','n','创伤'],['treaty','n','条约'],['trend','n','趋势'],['tribe','n','部落'],
    ['tribute','n','致敬'],['triumph','n','胜利'],['trophy','n','奖杯'],['troop','n','部队'],
    ['tube','n','管'],['tumor','n','肿瘤'],['tunnel','n','隧道'],['turmoil','n','动荡'],
    ['tutor','n','导师'],['tycoon','n','大亨'],['tyranny','n','暴政'],['undertaking','n','事业'],
    ['unemployment','n','失业'],['utility','n','公用事业'],['vacuum','n','真空'],['validity','n','有效性'],
    ['venture','n','企业'],['verdict','n','裁决'],['version','n','版本'],['vessel','n','容器'],
    ['veteran','n','老兵'],['vicinity','n','附近'],['villain','n','恶棍'],['violation','n','违反'],
    ['virtue','n','美德'],['visa','n','签证'],['volcano','n','火山'],['warfare','n','战争'],
    ['warranty','n','保修'],['weapon','n','武器'],['welfare','n','福利'],['wilderness','n','荒野'],
    ['workforce','n','劳动力'],['workshop','n','车间'],['wound','n','伤口'],['wreck','n','残骸'],
    ['zone','n','区域'],
  ],
  '高频形容词副词': [
    ['abstract','a','抽象的'],['abundant','a','丰富的'],['accurate','a','准确的'],['acute','a','急性的'],
    ['adequate','a','足够的'],['adjacent','a','相邻的'],['adverse','a','不利的'],['aesthetic','a','审美的'],
    ['aggressive','a','侵略性的'],['alert','a','警觉的'],['alien','a','外来的'],['allied','a','结盟的'],
    ['alternate','a','交替的'],['amateur','a','业余的'],['ambiguous','a','模糊的'],['ambitious','a','有雄心的'],
    ['ample','a','充足的'],['anonymous','a','匿名的'],['anxious','a','焦虑的'],['appropriate','a','适当的'],
    ['arbitrary','a','任意的'],['artificial','a','人工的'],['authentic','a','真正的'],['autonomous','a','自治的'],
    ['awkward','a','尴尬的'],['bare','a','赤裸的'],['barren','a','贫瘠的'],['beloved','a','心爱的'],
    ['beneficial','a','有益的'],['bitter','a','苦的'],['bizarre','a','奇怪的'],['bland','a','平淡的'],
    ['blank','a','空白的'],['bleak','a','荒凉的'],['blind','a','盲的'],['blunt','a','钝的'],
    ['bold','a','大胆的'],['bound','a','一定的'],['brave','a','勇敢的'],['brief','a','简短的'],
    ['brilliant','a','辉煌的'],['broad','a','广泛的'],['brutal','a','残忍的'],['bulk','a','大量的'],
    ['calm','a','平静的'],['capable','a','有能力的'],['casual','a','随意的'],['cautious','a','谨慎的'],
    ['chronic','a','慢性的'],['civic','a','公民的'],['civil','a','文明的'],['classic','a','经典的'],
    ['clinical','a','临床的'],['coherent','a','连贯的'],['collective','a','集体的'],['colonial','a','殖民的'],
    ['comparable','a','可比的'],['compatible','a','兼容的'],['competent','a','有能力的'],['comprehensive','a','全面的'],
    ['compulsory','a','强制的'],['concrete','a','具体的'],['confidential','a','机密的'],['conscious','a','有意识的'],
    ['consecutive','a','连续的'],['consistent','a','一致的'],['contemporary','a','当代的'],['controversial','a','有争议的'],
    ['conventional','a','传统的'],['convenient','a','方便的'],['convincing','a','令人信服的'],['core','a','核心的'],
    ['corporate','a','公司的'],['corresponding','a','对应的'],['costly','a','昂贵的'],['courteous','a','有礼貌的'],
    ['cozy','a','舒适的'],['credible','a','可信的'],['crucial','a','关键的'],['crude','a','粗糙的'],
    ['cumulative','a','累积的'],['curious','a','好奇的'],['decent','a','体面的'],['decisive','a','决定性的'],
    ['deliberate','a','故意的'],['delicate','a','精致的'],['dense','a','密集的'],['desperate','a','绝望的'],
    ['diplomatic','a','外交的'],['discreet','a','谨慎的'],['distinct','a','不同的'],['diverse','a','多样的'],
    ['divine','a','神圣的'],['domestic','a','国内的'],['dominant','a','主导的'],['doubtful','a','怀疑的'],
    ['drastic','a','剧烈的'],['dreadful','a','可怕的'],['dull','a','沉闷的'],['dynamic','a','动态的'],
    ['eager','a','渴望的'],['ecological','a','生态的'],['efficient','a','高效的'],['elaborate','a','精心的'],
    ['eligible','a','有资格的'],['elite','a','精英的'],['eloquent','a','雄辩的'],['embarrassing','a','尴尬的'],
    ['emerging','a','新兴的'],['eminent','a','杰出的'],['empirical','a','经验的'],['endless','a','无尽的'],
    ['enormous','a','巨大的'],['enthusiastic','a','热情的'],['entire','a','全部的'],['equivalent','a','等价的'],
    ['essential','a','必要的'],['eternal','a','永恒的'],['ethical','a','伦理的'],['evident','a','明显的'],
    ['evil','a','邪恶的'],['excessive','a','过度的'],['exotic','a','异国的'],['explicit','a','明确的'],
    ['exterior','a','外部的'],['extinct','a','灭绝的'],['extravagant','a','奢侈的'],['extreme','a','极端的'],
    ['fabulous','a','极好的'],['faint','a','微弱的'],['faithful','a','忠实的'],['familiar','a','熟悉的'],
    ['fatal','a','致命的'],['favorable','a','有利的'],['feasible','a','可行的'],['federal','a','联邦的'],
    ['feminine','a','女性的'],['fertile','a','肥沃的'],['fierce','a','凶猛的'],['fiscal','a','财政的'],
    ['flat','a','平坦的'],['fluent','a','流利的'],['fond','a','喜爱的'],['foolish','a','愚蠢的'],
    ['forbidden','a','禁止的'],['formal','a','正式的'],['formidable','a','可怕的'],['forthcoming','a','即将来临的'],
    ['fragile','a','脆弱的'],['frank','a','坦率的'],['frequent','a','频繁的'],['fruitful','a','富有成果的'],
    ['fundamental','a','基本的'],['furious','a','愤怒的'],['fussy','a','挑剔的'],['futile','a','徒劳的'],
    ['generous','a','慷慨的'],['genetic','a','遗传的'],['genuine','a','真正的'],['gigantic','a','巨大的'],
    ['global','a','全球的'],['gorgeous','a','华丽的'],['gradual','a','逐渐的'],['grateful','a','感激的'],
    ['grave','a','严重的'],['greedy','a','贪婪的'],['grim','a','严酷的'],['gross','a','总的'],
    ['guilty','a','有罪的'],['harsh','a','严厉的'],['hasty','a','匆忙的'],['hazardous','a','危险的'],
    ['hollow','a','空心的'],['holy','a','神圣的'],['horizontal','a','水平的'],['horrible','a','可怕的'],
    ['hostile','a','敌对的'],['humble','a','谦虚的'],['humid','a','潮湿的'],['identical','a','相同的'],
    ['idle','a','闲置的'],['ignorant','a','无知的'],['illegal','a','非法的'],['imaginative','a','有想象力的'],
    ['immense','a','巨大的'],['immune','a','免疫的'],['imperial','a','帝国的'],['implicit','a','含蓄的'],
    ['inadequate','a','不充分的'],['incredible','a','不可思议的'],['independent','a','独立的'],['indifferent','a','冷漠的'],
    ['indigenous','a','土著的'],['individual','a','个人的'],['industrial','a','工业的'],['inevitable','a','不可避免的'],
    ['inferior','a','低等的'],['infinite','a','无限的'],['influential','a','有影响力的'],['inherent','a','固有的'],
    ['initial','a','最初的'],['innocent','a','无辜的'],['insignificant','a','微不足道的'],['integral','a','不可缺少的'],
    ['intense','a','强烈的'],['interactive','a','互动的'],['interior','a','内部的'],['intimate','a','亲密的'],
    ['intuitive','a','直觉的'],['invisible','a','看不见的'],['ironic','a','讽刺的'],['irrational','a','不合理的'],
    ['irrelevant','a','不相关的'],['isolated','a','孤立的'],['keen','a','敏锐的'],['legitimate','a','合法的'],
    ['liable','a','有责任的'],['literal','a','字面的'],['lonely','a','孤独的'],['loyal','a','忠诚的'],
    ['magnificent','a','壮丽的'],['mainstream','a','主流的'],['mandatory','a','强制的'],['marginal','a','边缘的'],
    ['masculine','a','男性的'],['massive','a','大量的'],['mature','a','成熟的'],['medieval','a','中世纪的'],
    ['mere','a','仅仅的'],['metropolitan','a','大都市的'],['mighty','a','强大的'],['mild','a','温和的'],
    ['militant','a','好战的'],['minimal','a','最小的'],['minor','a','次要的'],['mobile','a','移动的'],
    ['moderate','a','适度的'],['modest','a','谦虚的'],['molecular','a','分子的'],['moral','a','道德的'],
    ['mortal','a','凡人的'],['municipal','a','市政的'],['mutual','a','相互的'],['naive','a','天真的'],
    ['naked','a','裸体的'],['nasty','a','令人不快的'],['native','a','本地的'],['naval','a','海军的'],
    ['neat','a','整洁的'],['negative','a','消极的'],['negligible','a','可忽略的'],['neutral','a','中立的'],
    ['noble','a','高贵的'],['nominal','a','名义上的'],['notable','a','值得注意的'],['noticeable','a','显著的'],
    ['notorious','a','臭名昭著的'],['nuclear','a','核的'],['objective','a','客观的'],['obsolete','a','过时的'],
    ['obvious','a','明显的'],['occasional','a','偶尔的'],['odd','a','奇怪的'],['offensive','a','冒犯的'],
    ['ongoing','a','持续的'],['opaque','a','不透明的'],['optional','a','可选的'],['oral','a','口头的'],
    ['organic','a','有机的'],['orthodox','a','正统的'],['outdoor','a','户外的'],['outer','a','外部的'],
    ['outstanding','a','杰出的'],['overall','a','总体的'],['overwhelming','a','压倒性的'],['partial','a','部分的'],
    ['passive','a','被动的'],['peculiar','a','奇特的'],['permanent','a','永久的'],['persistent','a','坚持的'],
    ['photographic','a','摄影的'],['physical','a','物理的'],['plain','a','简单的'],['pleasant','a','愉快的'],
    ['plentiful','a','丰富的'],['polar','a','极地的'],['portable','a','便携的'],['positive','a','积极的'],
    ['potential','a','潜在的'],['practically','ad','实际上'],['precious','a','珍贵的'],['precise','a','精确的'],
    ['predominant','a','主要的'],['pregnant','a','怀孕的'],['preliminary','a','初步的'],['premier','a','首要的'],
    ['premium','a','高级的'],['prevalent','a','流行的'],['primitive','a','原始的'],['principal','a','主要的'],
    ['prior','a','先前的'],['productive','a','生产的'],['professional','a','专业的'],['profitable','a','有利可图的'],
    ['profound','a','深刻的'],['progressive','a','进步的'],['prominent','a','突出的'],['prone','a','易于的'],
    ['proper','a','适当的'],['proportional','a','比例的'],['prospective','a','预期的'],['prosperous','a','繁荣的'],
    ['protective','a','保护的'],['provocative','a','挑衅的'],['prudent','a','谨慎的'],['psychiatric','a','精神病学的'],
    ['racial','a','种族的'],['radical','a','激进的'],['random','a','随机的'],['rational','a','理性的'],
    ['raw','a','生的'],['readily','ad','容易地'],['realistic','a','现实的'],['reasonable','a','合理的'],
    ['regardless','ad','不管'],['regional','a','区域的'],['reliable','a','可靠的'],['reluctant','a','不情愿的'],
    ['remarkable','a','显著的'],['renewable','a','可再生的'],['renowned','a','著名的'],['respective','a','各自的'],
    ['rigid','a','刚性的'],['robust','a','强健的'],['romantic','a','浪漫的'],['rough','a','粗糙的'],
    ['royal','a','王室的'],['rural','a','农村的'],['sacred','a','神圣的'],['savage','a','野蛮的'],
    ['scarce','a','稀缺的'],['scenic','a','风景优美的'],['secure','a','安全的'],['selective','a','选择性的'],
    ['senior','a','高级的'],['sensible','a','明智的'],['sensitive','a','敏感的'],['severe','a','严重的'],
    ['shallow','a','浅的'],['sharp','a','锋利的'],['sheer','a','纯粹的'],['skeptical','a','怀疑的'],
    ['slender','a','苗条的'],['slight','a','轻微的'],['slim','a','苗条的'],['smooth','a','光滑的'],
    ['sober','a','清醒的'],['solemn','a','庄严的'],['solid','a','固体的'],['sophisticated','a','复杂的'],
    ['sour','a','酸的'],['sovereign','a','主权的'],['spare','a','备用的'],['spectacular','a','壮观的'],
    ['spiritual','a','精神的'],['spontaneous','a','自发的'],['stable','a','稳定的'],['static','a','静态的'],
    ['steady','a','稳定的'],['steep','a','陡峭的'],['stem','a','干的'],['stern','a','严厉的'],
    ['stiff','a','僵硬的'],['straightforward','a','直接的'],['strategic','a','战略的'],['strict','a','严格的'],
    ['striking','a','引人注目的'],['stubborn','a','固执的'],['stunning','a','惊人的'],['subjective','a','主观的'],
    ['subtle','a','微妙的'],['successive','a','连续的'],['sufficient','a','足够的'],['superficial','a','表面的'],
    ['superior','a','优越的'],['supreme','a','至高的'],['sustainable','a','可持续的'],['swift','a','迅速的'],
    ['symbolic','a','象征的'],['sympathetic','a','同情的'],['synthetic','a','合成的'],['systematic','a','系统的'],
    ['temporary','a','临时的'],['tender','a','温柔的'],['tense','a','紧张的'],['terminal','a','终端的'],
    ['thorough','a','彻底的'],['tight','a','紧的'],['timely','a','及时的'],['tolerant','a','容忍的'],
    ['toxic','a','有毒的'],['tragic','a','悲惨的'],['tremendous','a','巨大的'],['tropical','a','热带的'],
    ['turbulent','a','动荡的'],['typical','a','典型的'],['ultimate','a','最终的'],['unanimous','a','一致的'],
    ['uncertain','a','不确定的'],['underlying','a','潜在的'],['undoubtedly','ad','毫无疑问'],['unfair','a','不公平的'],
    ['unfortunate','a','不幸的'],['uniform','a','统一的'],['unprecedented','a','史无前例的'],['unlikely','a','不太可能的'],
    ['unprecedented','a','空前的'],['upper','a','上面的'],['urban','a','城市的'],['urgent','a','紧急的'],
    ['vacant','a','空的'],['vague','a','模糊的'],['valid','a','有效的'],['valuable','a','有价值的'],
    ['verbal','a','口头的'],['versatile','a','多才多艺的'],['vertical','a','垂直的'],['vicious','a','恶毒的'],
    ['vigorous','a','有活力的'],['virtual','a','虚拟的'],['visible','a','可见的'],['vital','a','至关重要的'],
    ['vivid','a','生动的'],['volatile','a','易变的'],['voluntary','a','自愿的'],['vulnerable','a','脆弱的'],
    ['weird','a','怪异的'],['wholesale','a','批发的'],['wicked','a','邪恶的'],['widespread','a','广泛的'],
    ['willing','a','愿意的'],['worthwhile','a','值得的'],['worthy','a','值得的'],
  ],
};

// ===================== BUILD OUTPUT =====================

// Add new roots
const newRootData = newRoots.map(r => {
  const words = [];
  r.words.forEach(([word, pos, meaning]) => addWord(words, word, pos, meaning));
  return {
    id: r.id,
    root: r.root,
    meaning: r.meaning,
    origin: r.origin,
    color: r.color,
    level: r.level,
    words,
  };
}).filter(r => r.words.length > 0);

// Merge roots (avoid duplicate root ids)
const existingRootIds = new Set(existing.roots.map(r => r.id));
const mergedRoots = [
  ...existing.roots,
  ...newRootData.filter(r => !existingRootIds.has(r.id)),
];

// Merge supplements
const mergedSupplement = { ...existing.supplement };
Object.entries(supplementExpansion).forEach(([category, rawWords]) => {
  const filtered = [];
  rawWords.forEach(([word, pos, meaning]) => addWord(filtered, word, pos, meaning));
  if (!mergedSupplement[category]) {
    mergedSupplement[category] = filtered;
  } else {
    mergedSupplement[category] = [...mergedSupplement[category], ...filtered];
  }
});

// Count
let totalRootWords = 0;
mergedRoots.forEach(r => totalRootWords += r.words.length);
let totalSuppWords = 0;
Object.values(mergedSupplement).forEach(arr => totalSuppWords += arr.length);
const total = totalRootWords + totalSuppWords;

console.log('=== Expanded Database ===');
console.log('Roots:', mergedRoots.length);
console.log('Root words:', totalRootWords);
console.log('Supplement categories:', Object.keys(mergedSupplement).length);
Object.entries(mergedSupplement).forEach(([k,v]) => console.log(`  ${k}: ${v.length}`));
console.log('Supplement words:', totalSuppWords);
console.log('TOTAL:', total);
console.log('Unique in set:', existingWords.size);

// Write output
const output = {
  version: '2.0',
  generatedAt: new Date().toISOString(),
  stats: {
    rootCount: mergedRoots.length,
    rootWordCount: totalRootWords,
    supplementWordCount: totalSuppWords,
    totalWordCount: total,
  },
  roots: mergedRoots,
  supplement: mergedSupplement,
};

const outPath = path.join(__dirname, '..', 'src', 'data', 'wordDatabaseRaw.json');
fs.writeFileSync(outPath, JSON.stringify(output), 'utf8');
console.log('\nWritten to', outPath);
console.log('File size:', (fs.statSync(outPath).size / 1024).toFixed(0), 'KB');
